### ISSUE TITLE
Keyboard shortcuts do not seem to work on Windows

### ISSUE THREAD

**Issue by lietu** [buttercup/buttercup#195]
It seems Ctrl+C to copy the password does not work, at least not the way I expect it to. I click on an entry, and press Ctrl+C and my clipboard contents don't change at all. Clicking the "Copy" -icon next to the password does work though.

**Comment by perry-mitchell** [comment]
Thanks @lietu! Unfortunately our windows development processes are somewhat non-existent (although we **want** to support windows just as well as Mac & Linux). Hopefully yourself or someone might consider making a PR at some point to fix it, otherwise it might be a bit of a slow burn until we can wrangle together some windows machines (hopefully soon).

**Comment by lietu** [comment]
Seems like this is a thing with Chrom* having hardcoded handling for certain key bindings, at least on Windows:

https://github.com/electron/electron/issues/7165

Looks like a workaround is on the renderer-side to do some `window.addEventListener('keyup', ..., true);` type thing or use Mousetrap as suggested by Electron docs:

https://github.com/electron/electron/blob/master/docs/tutorial/keyboard-shortcuts.md#shortcuts-within-a-browserwindow

I was at least able to get the event for Ctrl+C on the renderer side.

**Comment by perry-mitchell** [comment]
Seems to also not work on linux (ctrl-c on entries).

**Comment by sallar** [comment]
@perry-mitchell @lietu 
the current implementation overwrites the default `Ctrl/Cmd+C` key, and it's adding a lot of unnecessary issues. What if we change the shortcuts to another set? Like `Ctrl/Cmd+Alt+C` or something similar?

**Comment by lietu** [comment]
That would make the keyboard shortcuts work, but be less useful. I.e. people would not find them intuitive, which is an important bit about keyboard shortcuts. The solution should follow the principle of least astonishment imo.

I think likely the correct solution is to set up some sort of keyboard shortcut definition somewhere that can be reused both when building the menu (if for no other reason just to show the shortcuts correctly) and on the client-side using Mousetrap. It's a bit of extra work, but if done well it shouldn't be THAT much extra work.

If you want, I can try to take a look at how that kind of a solution could be implemented? No promises on schedule though.

**Comment by perry-mitchell** [comment]
@lietu @sallar I agree - I think the shortcuts should be obvious. The less help users need to look up the better. Even if it's more painful I'd opt for the easier use.

**Comment by sallar** [comment]
@lietu This is fixed and will go out in next release :)

**Comment by TomaterID** [comment]
> @lietu This is fixed and will go out in next release :)

Well, I don't really see this fixed. At leaset Ctrl+C and Ctrl+A still do not work in 14.x on Windows as of Feb 2022...
